### ISSUE TITLE
Error [ERR_OUT_OF_RANGE]

### ISSUE THREAD

**Issue by ItsNoted** [IsaacInsoll/PICR#7]
Error happened: RangeError [ERR_OUT_OF_RANGE]: The value of "interval" is out of range. It must be an integer. Received NaN

Any idea what this is from? Just using the docker compose you provided.

**Comment by IsaacInsoll** [comment]
Wow, didn’t know anybody else was using this yet so I’m happy slot see someone else using it. 

What build are you on? Does this happen at startup or when you take a certain action? Is there any more info in the server log?
